package com.lowlevelsubmarine.youtube_api;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class AGenDescExtractor {

    private static final String AGEN_DESC_START = "Provided to YouTube by ";
    private static final Pattern AD_PATTERN = Pattern.compile("([^·\\n\\r]+) · (.+)\\n\\n(.+)\\n\\n[\\S\\s]*Auto-generated by YouTube\\.$");

    private Matcher matcher;

    public static boolean isAGenDesc(String desc) {
        return desc.startsWith(AGEN_DESC_START);
    }

    public AGenDescExtractor(String videoDescription) throws InvalidDescriptionException {
        //Check without regex first to save the parsing time
        if (!isAGenDesc(videoDescription)) {
            throw new InvalidDescriptionException();
        }
        this.matcher = AD_PATTERN.matcher(videoDescription);
        if (!this.matcher.find()) {
            throw new InvalidDescriptionException();
        }
    }

    public AGenDesc getAGenDesc() {
        return new AGenDesc(matcher.group(1), matcher.group(2), matcher.group(3));
    }

    public class InvalidDescriptionException extends Exception {}

}